version: "3.9"

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    env_file:
  # DBっ情報であるPMA_〇〇の値
      - ./envs/db/_.env
      - ./envs/db/.env
    # environment:
    depends_on:
        - db

  # [プロジェクト共通]webサーバーのコンテナ(プロジェクトごとにports,depends_on,volumesを設定)
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    # ports:
      # - "81:81" # app1 のポート。nginxのdefault.confで設定している
      # - "82:82" # hoge のポート。nginxのdefault.confで設定している
    # depends_on:
      # - app1
      # - hoge
    restart: always
    volumes:
      # - ./../alpen/app/:/app/alpen
      - ./../app1/app/:/app/app1
      - ./../ucrm/app/:/app/ucrm
      - ./../sk_marche/app/:/app/sk_marche
      - ./../index/app/:/app/index
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf

  # 上記webサービスでのURLをSSL化
  ssl:
    build:
      context: .
      dockerfile: ./docker/ssl/Dockerfile
    ports:
      - '80:80'  # http通信のポート、Let's Encryptが確認アクセスするので必須。
      - '443:443'  ## ssl化通信のポート、必須。
    # links:
    #   - web
    restart: always
    env_file:
      - ./envs/ssl/.env # 「SSL化URL -> nginx:ポート番号」の設定
    environment:
        CLIENT_MAX_BODY_SIZE: '0'
    volumes:
      - ./docker/ssl/https_portal:/var/lib/https-portal


  # [プロジェクト共通]dbサーバーのコンテナ
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    # ports:
    #   - "3306:3306"
    env_file:
      - ./envs/db/.env
      - ./envs/db/_.env
    environment:
      TZ: 'UTC'
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  default:
    name: db_web_ssl
    external: true

volumes:
  mysql-volume:
  
